version=0.1



[[datasets]]

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="Hall_2012"

  [datasets.publication]
  doi= "10.1109/TSE.2011.103"

  [datasets.data]
  doi="10.5281/zenodo.1162952"

  [datasets.scripts]
  compose="compose.py Hall_2012"

[[datasets]]
  # publication doesn't have DOI or OpenAlex reference

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

 key="Wahono_2015"
 active=false
 note="The publication doesn't have a record in the OpenAlex database."

 [datasets.publication]
  # http://journal.ilmukomputer.org/index.php?journal=jse&page=article&op=view&path%5B%5D=47
 doi= ""

 [datasets.data]
 doi="10.5281/zenodo.1162952"


[[datasets]]

  # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="Radjenovic_2013"

  [datasets.publication]
  doi= "10.1016/j.infsof.2013.02.009"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]

 # Part of Yu et al. 2018 https://doi.org/10.1007/s10664-017-9587-0

  key="Kitchenham_2010"
  active=false
  note="(IEEE) URLs in the dataset don't match the original records. Reliability concern."

  [datasets.publication]
  doi= "10.1016/j.infsof.2010.03.006"

  [datasets.data]
  doi="10.5281/zenodo.1162952"

[[datasets]]
  # Processes 1 dataset (https://osf.io/tnxju/)

  key="Donners_2021"

  [datasets.publication]

  doi= "10.1007/s40262-021-01042-w"

  [datasets.data]

  doi="https://osf.io/tnxju/"

[[datasets]]

  key="Meijboom_2022"

  [datasets.publication]

  doi= "10.1007/s40259-021-00508-4"

  [datasets.data]

  doi="https://osf.io/4cdku/"
[[datasets]]

  key="Valk_2021"

  [datasets.publication]

  doi= "10.1111/obr.13376"

  [datasets.data]

  doi="https://osf.io/download/gmjcv/"

[[datasets]]

  key="Smid_2020"

  [datasets.publication]

  doi= "10.1080/10705511.2019.1577140"

  [datasets.data]

  doi="https://osf.io/gxams"

[[datasets]]

  key="Brouwer_2019"
  active=false

  [datasets.publication]

  doi= "10.1016/j.cpr.2019.101773"

  [datasets.data]

  doi="https://osf.io/py7ek"

[[datasets]]

  key="Appenzeller-Herzog_2020"

  [datasets.publication]

  doi= "10.1111/liv.14179"

  [datasets.data]

  doi="10.5281/zenodo.3625931"

[[datasets]]

  # original study https://doi.org/10.1002/ebm2.24

  key="Bannach-Brown_2019"

  [datasets.publication]

  doi= "10.1186/s13643-019-0942-7"

  [datasets.data]

  doi="https://doi.org/10.5281/zenodo.151190"

[[datasets]]

  key="Bos_2018"

  [datasets.publication]

  doi= "10.1016/j.jalz.2018.04.007"

  [datasets.data]

  doi="https://osf.io/w3kbq/"

[[datasets]]

  key="Cohen_2006_ACEInhibitors"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py ACEInhibitors"

[[datasets]]

  key="Cohen_2006_CalciumChannelBlockers"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py CalciumChannelBlockers"


[[datasets]]

  key="Cohen_2006_ProtonPumpInhibitors"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py ProtonPumpInhibitors"


[[datasets]]

  key="Cohen_2006_ADHD"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py ADHD"

[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Nelson_2002"

  [datasets.publication]

  doi= "10.1001/jama.288.7.872"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Estrogens --name Nelson_2002"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Chou_2004"

  [datasets.publication]

  doi= "10.1016/j.jpainsymman.2004.05.002"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py SkeletalMuscleRelaxants --name Chou_2004"



[[datasets]]

  key="Cohen_2006_Antihistamines"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Antihistamines"

[[datasets]]

  key="Cohen_2006_NSAIDS"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py NSAIDS"


[[datasets]]

  key="Cohen_2006_Statins"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Statins"



[[datasets]]

  key="Cohen_2006_AtypicalAntipsychotics"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py AtypicalAntipsychotics"

[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Chou_2003"

  [datasets.publication]

  doi= "10.1016/j.jpainsymman.2003.03.003"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Opioids --name Chou_2003"


[[datasets]]

  key="Cohen_2006_Triptans"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Triptans"



[[datasets]]

  key="Cohen_2006_BetaBlockers"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py BetaBlockers"

[[datasets]]

  key="Cohen_2006_OralHypoglycemics"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py OralHypoglycemics"


[[datasets]]

  key="Cohen_2006_UrinaryIncontinence"
  active=false
  note="Original publication not found"

  [datasets.publication]
  doi= "10.1197/jamia.M1929"

  [datasets.data]

  doi="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py UrinaryIncontinence"

[[datasets]]

  key="Nagtegaal_2019"
  active=false
  note="Dataset technically corrupted."

  [datasets.publication]

  doi= "10.30636/jbpa.22.71"

  [datasets.data]

  doi="https://doi.org/10.7910/DVN/WMGPGZ/HY6N2S"


[[datasets]]

  # Note that this dataset is also used for another systematic review:
  # https://doi.org/10.1080/00273171.2017.1412293

  key="van_de_Schoot_2017"
  note="Issue with year of publication (2017). 2016 or 2018?"

  [datasets.publication]

  doi= "10.1080/10705511.2016.1247646"

  [datasets.data]

  doi="https://doi.org/10.17605/OSF.IO/VW3T7"


[[datasets]]

  key="van_Dis_2020"

  [datasets.publication]

  doi= "10.1001/jamapsychiatry.2019.3986"

  [datasets.data]

  doi="https://osf.io/4d9tu/"


[[datasets]]

  key="Wolters_2018"

  [datasets.publication]

  doi= "10.1016/j.jalz.2018.01.007"

  [datasets.data]

  doi="https://osf.io/sxzjg/"


[[datasets]]

  key="Leenaars_2019"

  [datasets.publication]
  doi= "10.5334/jcr.183"

  [datasets.data]
  doi="10.17605/OSF.IO/PH56S"
