version=0.1



[[datasets]]

  key="Hall_2012"

  [datasets.collection]
  doi="10.1007/s10664-017-9587-0"

  [datasets.publication]
  doi="10.1109/TSE.2011.103"

  [datasets.data]
  doi="10.5281/zenodo.1162952"

  [datasets.scripts]
  compose="compose.py Hall_2012"


[[datasets]]
  # publication doesn't have DOI or OpenAlex reference

 key="Wahono_2015"
 active=false
 note="The publication doesn't have a record in the OpenAlex database."

  [datasets.collection]
  doi="10.1007/s10664-017-9587-0"

 [datasets.publication]
  url="http://journal.ilmukomputer.org/index.php?journal=jse&page=article&op=view&path%5B%5D=47"

 [datasets.data]
 doi="10.5281/zenodo.1162952"


[[datasets]]

  key="Radjenovic_2013"

  [datasets.collection]
  doi="10.1007/s10664-017-9587-0"

  [datasets.publication]
  doi="10.1016/j.infsof.2013.02.009"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]

  key="Kitchenham_2010"
  active=false
  note="(IEEE) URLs in the dataset don't match the original records. Reliability concern."

  [datasets.collection]
  doi="10.1007/s10664-017-9587-0"

  [datasets.publication]
  doi="10.1016/j.infsof.2010.03.006"

  [datasets.data]
  doi="10.5281/zenodo.1162952"


[[datasets]]
  # Processes 1 dataset (https://osf.io/tnxju/)

  key="Donners_2021"

  [datasets.publication]

  doi="10.1007/s40262-021-01042-w"

  [datasets.data]

  url="https://osf.io/tnxju/"


[[datasets]]

  key="Meijboom_2021"

  [datasets.publication]

  doi="10.1007/s40259-021-00508-4"

  [datasets.data]

  url="https://osf.io/4cdku/"
[[datasets]]

  key="Valk_2021"
  note="Should be Van der Valk"

  [datasets.publication]

  doi="10.1111/obr.13376"

  [datasets.data]

  doi="10.17605/OSF.IO/WDZH5"


[[datasets]]

  key="Smid_2020"

  [datasets.publication]

  doi="10.1080/10705511.2019.1577140"

  [datasets.data]

  doi="10.17605/OSF.IO/PUQ7X"


[[datasets]]

  key="Brouwer_2019"

  [datasets.publication]

  doi="10.1016/j.cpr.2019.101773"

  [datasets.data]

  doi="10.17605/OSF.IO/R45YZ"


[[datasets]]

  key="Appenzeller-Herzog_2019"

  [datasets.publication]

  doi="10.1111/liv.14179"

  [datasets.data]

  doi="10.5281/zenodo.3625931"


[[datasets]]

  # original study https://doi.org/10.1002/ebm2.24

  key="Bannach-Brown_2019"

  [datasets.publication]

  doi="10.1186/s13643-019-0942-7"

  [datasets.data]

  doi="10.5281/zenodo.151190"


[[datasets]]

  key="Bos_2018"

  [datasets.publication]

  doi="10.1016/j.jalz.2018.04.007"

  [datasets.data]

  url="https://osf.io/w3kbq/"


[[datasets]]

  key="Cohen_2006_ACEInhibitors"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py ACEInhibitors"


[[datasets]]

  key="Cohen_2006_CalciumChannelBlockers"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py CalciumChannelBlockers"


[[datasets]]

  key="Cohen_2006_ProtonPumpInhibitors"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py ProtonPumpInhibitors"


[[datasets]]

  key="Cohen_2006_ADHD"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py ADHD"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Nelson_2002"

  [datasets.publication]

  doi="10.1001/jama.288.7.872"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Estrogens --name Nelson_2002"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Chou_2004"

  [datasets.publication]

  doi="10.1016/j.jpainsymman.2004.05.002"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py SkeletalMuscleRelaxants --name Chou_2004"


[[datasets]]

  key="Cohen_2006_Antihistamines"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Antihistamines"


[[datasets]]

  key="Cohen_2006_NSAIDS"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py NSAIDS"


[[datasets]]

  key="Cohen_2006_Statins"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Statins"


[[datasets]]

  key="Cohen_2006_AtypicalAntipsychotics"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py AtypicalAntipsychotics"


[[datasets]]

  # Part of Cohen et al. 2006 https://doi.org/10.1197/jamia.M1929

  key="Chou_2003"

  [datasets.publication]

  doi="10.1016/j.jpainsymman.2003.03.003"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Opioids --name Chou_2003"


[[datasets]]

  key="Cohen_2006_Triptans"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py Triptans"


[[datasets]]

  key="Cohen_2006_BetaBlockers"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py BetaBlockers"


[[datasets]]

  key="Cohen_2006_OralHypoglycemics"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py OralHypoglycemics"


[[datasets]]

  key="Cohen_2006_UrinaryIncontinence"
  active=false
  note="Original publication not found"

  [datasets.collection]
  doi="10.1197/jamia.M1929"

  [datasets.data]

  url="https://dmice.ohsu.edu/cohenaa/systematic-drug-class-review-data.html"

  [datasets.scripts]
  compose="compose.py UrinaryIncontinence"


[[datasets]]

  key="Nagtegaal_2019"
  active=false
  note="Dataset technically corrupted."

  [datasets.publication]

  doi="10.30636/jbpa.22.71"

  [datasets.data]

  doi="10.7910/DVN/WMGPGZ/HY6N2S"


[[datasets]]

  # Note, this dataset is also used for another systematic review:
  # https://doi.org/10.1080/00273171.2017.1412293

  key="van_de_Schoot_2017"

  [datasets.publication]

  doi="10.1080/10705511.2016.1247646"

  [datasets.data]

  doi="10.17605/OSF.IO/VW3T7"


[[datasets]]

  key="van_Dis_2020"

  [datasets.publication]

  doi="10.1001/jamapsychiatry.2019.3986"

  [datasets.data]

  url="https://osf.io/4d9tu/"


[[datasets]]

  key="Wolters_2018"

  [datasets.publication]

  doi="10.1016/j.jalz.2018.01.007"

  [datasets.data]

  url="https://osf.io/sxzjg/"


[[datasets]]

  key="Leenaars_2019"

  [datasets.publication]
  doi="10.5334/jcr.183"

  [datasets.data]
  doi="10.17605/OSF.IO/PH56S"


[[datasets]]

  key="Welling_2021"

  [datasets.publication]
  doi="10.1159/000520718"

  [datasets.data]
  doi="10.17605/OSF.IO/E5JNB"


[[datasets]]

  key="Menon_2022"

  [datasets.publication]
  doi="10.1080/10408444.2022.2082917"

  [datasets.data]
  url="https://osf.io/9jzsu"


[[datasets]]

  key="van_der_Waal_2022"

  [datasets.publication]
  doi="10.1016/j.jgo.2022.09.012"

  [datasets.data]
  doi="10.5281/zenodo.7308296"


[[datasets]]

  key="Muthu_2021"

  [datasets.publication]
  doi="10.1097/BRS.0000000000003645"

  [datasets.data]
  url="https://osf.io/68ezp"


[[datasets]]

  key="Muthu_2022"

  [datasets.publication]
  doi="http://doi.org/10.13105/wjma.v10.i3.162"

  [datasets.data]
  url="https://osf.io/e2yz3/"


[[datasets]]

  key="Jeyaraman_2020"

  [datasets.publication]
  doi="10.1177/1947603520951623"

  [datasets.data]
  url="https://osf.io/8drsc/"


[[datasets]]

  key="Moran_2021"

  [datasets.publication]
  doi="10.1111/brv.12655"

  [datasets.data]
  doi="10.17605/OSF.IO/3TPHJ"


[[datasets]]

  key="Kwok_2020"
  active=false
  note="License issue"

  [datasets.publication]
  doi="10.3390/v12010107"

  [datasets.data]
  doi="10.17605/OSF.IO/5S27M"


[[datasets]]

  key="Oud_2018"

  [datasets.publication]
  doi="10.1177/0004867418791257"

  [datasets.data]
  url="https://osf.io/pjr97"


[[datasets]]

  key="Wassenaar_2017"

  [datasets.publication]
  doi="10.1289/ehp1233"

  [datasets.data]
  doi="10.1186/s13643-016-0263-z"


[[datasets]]

  key="Rooney_2015"

  [datasets.collection]
  doi="10.1186/s13643-016-0263-z"

  [datasets.publication]
  doi="10.1007/978-3-319-15518-0_16"

  [datasets.data]
  doi="10.1186/s13643-016-0263-z"


[[datasets]]

  key="Walker_2018"

  [datasets.collection]
  doi="10.1186/s13643-016-0263-z"

  [datasets.publication]
  doi="10.1016/j.envint.2017.12.032"

  [datasets.data]
  doi="10.1186/s13643-016-0263-z"


[[datasets]]

  key="Leenaars_2020"

  [datasets.collection]
  doi="10.1186/s13643-016-0263-z"

  [datasets.publication]
  doi="10.3390/ani10061047"

  [datasets.data]
  doi="10.17605/OSF.IO/T7GYR"


[[datasets]]

  key="Sep_2021"

  [datasets.publication]
  doi="10.1371/journal.pone.0249102"

  [datasets.data]
  doi="10.17605/OSF.IO/GY2MC"
