name: "Render metadata"
on:
  pull_request

jobs:
  render-metadata-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Render
        run: |
          python metadata.py
          python render_wordcloud.py
